# Base configs
baseurl: "https://mcasellas.com"
# baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "G-Z5WLMK71GC"

# UI configs
title: "Marc Casellas"
subtitle: "Fotografia"
author: "Marc Casellas"
header:
 title: "Marc Casellas"
 subtitle: "Fotografia"
footer:
 name: "Hola, sóc en Marc"
 bio: "Nascut a la comarca d'Osona, Catalunya. Sóc enginyer informàtic de professió i un apassionat de la ràdio i la fotografia."
 github: "A través de la fotografia de carrer i de viatge busco capturar instants espontanis i històries úniques, sense deixar de banda la calma i la bellesa de la fotografia de paisatge. Aquest espai és una petita mostra del meu univers visual, a mode de portfolio."
# web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  twitter: "https://www.twitter.com/casellas98"
  instagram: "https://www.instagram.com/marc.casellas"
  #dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://in.linkedin.com/in/casellas98"
  github: "https://www.github.com/mcasellas"
